/** پیش‌فرض‌های کارخانه‌ای. */
export const DEFAULT_TABLE_CONFIG = {
    paginator: true,
    rows: 10,
    rowsPerPageOptions: [10, 20, 50],
    showCurrentPageReport: true,
    globalSearch: true,
    columnFilters: false,
    selectable: false,
    selectionMode: 'multiple',
    selectionToolbar: true,
    selectAllAcrossPages: true,
    sortMode: 'single',
    striped: true,
    gridlines: false,
    size: 'normal',
    columnToggle: false,
    rowExpansion: false,
    rowGroupField: '',
    rowGroupMode: 'rowspan',
    reorderableRows: false,
    editable: false,
    virtualScroll: false,
    virtualScrollItemSize: 46,
    scrollHeight: '',
    exportable: false,
    exportFilename: 'export',
    caption: '',
    dateFormat: 'yyyy/MM/dd',
    mobileBreakpoint: 768,
    mobilePageSize: 10,
    emptyMessage: 'موردی یافت نشد.',
};
